---
title: "covid interesting founding"
author: "Jiesen cui"
date: 2020-09-27T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Abstract


# Introduction


# Dicuss


# Code 

```{r code}

library(opendatatoronto)
library(dplyr)
library(tidyverse)
# get package
package <- show_package("64b54586-6180-4485-83eb-81e8fae3b8fe")
package

# get all resources for this package
resources <- list_package_resources("64b54586-6180-4485-83eb-81e8fae3b8fe")

# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))

# load the first datastore resource as a sample
data <- filter(datastore_resources, row_number()==1) %>% get_resource()
data

covid = data %>%
           select("Age Group","Reported Date","Source of Infection")
covid = covid %>% 
  dplyr::filter(!is.na(`Age Group`))
covid = covid %>% 
  dplyr::filter(!is.na(`Source of Infection`))

covid$`Age Group` <- ifelse(covid$`Age Group` == "19 and younger",  10, covid$`Age Group`);
covid$`Age Group` <- ifelse(covid$`Age Group` == "20 to 29 Years",  20, covid$`Age Group`);
covid$`Age Group` <- ifelse(covid$`Age Group` == "30 to 39 Years",  30, covid$`Age Group`);  
covid$`Age Group` <- ifelse(covid$`Age Group` == "40 to 49 Years",  40, covid$`Age Group`);  
covid$`Age Group` <- ifelse(covid$`Age Group` == "50 to 59 Years",  50, covid$`Age Group`);  
covid$`Age Group` <- ifelse(covid$`Age Group` == "60 to 69 Years",  60, covid$`Age Group`); 
covid$`Age Group` <- ifelse(covid$`Age Group` == "70 to 79 Years",  70, covid$`Age Group`);  
covid$`Age Group` <- ifelse(covid$`Age Group` == "80 to 89 Years",  80, covid$`Age Group`); 
covid$`Age Group` <- ifelse(covid$`Age Group` == "90 and older",  90, covid$`Age Group`); 
covid$`Age Group` <- ifelse(covid$`Age Group` == "NaN",  0, covid$`Age Group`); 

covid$`Source of Infection` <- ifelse(covid$`Source of Infection` == "Travel" , 0, covid$`Source of Infection`)
covid$`Source of Infection` <- ifelse(covid$`Source of Infection` ==  "Close contact", 1, covid$`Source of Infection`)
covid$`Source of Infection` <- ifelse(covid$`Source of Infection` ==  "Institutional" , 2, covid$`Source of Infection`)
covid$`Source of Infection` <- ifelse(covid$`Source of Infection` ==  "Healthcare"  , 3, covid$`Source of Infection`)
covid$`Source of Infection` <- ifelse(covid$`Source of Infection` ==   "Community"    , 4, covid$`Source of Infection`)
covid$`Source of Infection` <- ifelse(covid$`Source of Infection` ==   "N/A - Outbreak associated"    , 5, covid$`Source of Infection`)
covid$`Source of Infection` <- ifelse(covid$`Source of Infection` ==    "Unknown/Missing"   , 6, covid$`Source of Infection`)
covid$`Source of Infection` <- ifelse(covid$`Source of Infection` ==     "Pending"   , 7, covid$`Source of Infection`)


ggplot(data = covid, aes(x = `Age Group` )) + stat_count(color = 'grey',fill = 'pink')
ggplot(data = covid, aes(x = `Source of Infection`)) + stat_count(color = 'grey',fill = 'blue')


```


# Including Plots

You can also embed plots. See Figure \@ref(fig:pie) for example:

``` 
```
